config/routes.rb
Rails.application.routes.draw do
 root "homes#top"
  get "/" => "homes#top"
  patch "books/:id" => "books#update", as:"update_book"
  delete "books/:id" => "books#destroy", as:"destroy_book"
 
   resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  
  validates :title,presence: true
  validates :body,presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created." 
    redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated." 
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    flash[:notice] = "Book was successfully deleted." 
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<div id= "error_exprannation">
 
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<%= form_with model:@book, url: update_book_path(@book.id), method: :patch do |f| %>

  <div class= "field">
   <label for = "book_title">本のタイトル</label>
   <%= f.text_field :title %>
  </div>
  
  <div class= "field">
   <label for = "book_title">感想</label>
   <%= f.text_area :body %>
  </div>
 
  <div class = "actions">
   <%= f.submit "Update Book"  %>
  </div>
  
  <%= link_to "Show", book_path(@book.id) %>
 |
  <%= link_to "Back", books_path %>

  
  
<% end %>

app/views/books/index.html.erb
   <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

  <h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>本のタイトル</th>
      <th>感想</th>
      <th colspan= "3"></th>
    </tr>
  </thead>
  <tboday>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy",destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    </tr>
    <% end %>
  </tboday>
</table>






 <h2>New book</h2>
 
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

 

<%= form_with model: @book, local:true do |f| %>
 
  <div class= "field">
   <label for = "book_title">本のタイトル</label>
   <%= f.text_field :title %>
  </div>
  
  <div class= "field">
   <label for = "book_title">感想</label>
   <%= f.text_area :body %>
  </div>
 
  <div class = "actions">
   <%= f.submit "Create Books"  %>
  </div>

<% end %>
  

app/views/books/show.html.erb
   <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
<p><strong>本のタイトル：</strong><%= @book.title %></p>

<p><strong>感想：</strong><%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
    <h1 class = "title">
      ようこそ
      <strong>Bookers</strong>
      へ！</h1>

    <p class = "top-comment">
      <strong>Bookers</strong> では、さまざまな書類に関するあなたの意見や</p>
    <p class = "top-comment">印象を共有し交換することができます</p>

    <p><a href = "/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>